version: "3.3"

services:
    api-rest-laravel:
        build: ./
        ports:
            - 8000:8000
        env_file:
            - .env
        restart: always
        depends_on:
            - db
        networks:
            - docker

    db:
        image: mysql
        restart: always
        ports:
            - 3308:3306
        env_file:
            - .env
        volumes:
            - .docker/dbdata:/var/lib/mysql
        networks:
            - docker

networks:
    docker:
        driver: bridge
